### ISSUE TITLE
Repo Refactoring for Open-Source Release

### ISSUE THREAD

**Issue by aqzhen** [owlprotocol/contracts#208]

**Comment by corbanvilla** [comment]
### Publishing Checklist
- [x] Finish migrating from `nft-launcher-contracts-sol`
  - [x] ~~Migrate tests (closes #192) (currently assigned @corbanvilla)~~
  - [x] Delete folder (currently assigned @corbanvilla)
- [x] Merge working things into `owlprotocol-contracts/master` - **hold off on this**
  - [x] Move all contracts `*![Crafter]`
  - [x] Move all tests `*![Crafter]`
  - [x] Update `ERC165` and `version` tests to pass with removed contracts
- [x] Docs creation
  - [x] vectorize `draw.io`
  - [x] General repository readme (currently assigned @corbanvilla)
  - [x] Publish on github pages (currently assigned @corbanvilla)
  - [x] Assess and edit current `Crafter` NatSpec docs, add to if needed.
  - [x] **Example flows:** (currently assigned @aqzhen) (assigned @corbanvilla to finish Minter)
    - [x] How should a user interact with Crafter? (assigned @aqzhen)
      - What functions should they be interacting with?
      - What do typical args look like?
      - Where can they find more documentation (link to docusaurus API ref)
    - [x] How should a game developer interact with Crafter? (assigned @aqzhen)
      - What functions should they be interacting with?
      - What do typical args look like?
      - Where can they find more documentation (link to docusaurus API ref)
- [x] Publish NPM package
  - [x] Include `types` directory with `web3, truffle, ethers` types (assigned @corbanvilla)
- [x] Final cleanup
  - [x] Remove `.env.test`
  - [x] `CrafterMinter` fixes (currently assigned @aqzhen)
  - [x] Would be nice if CI tests started passing
  - [x] Rename repo to `contracts`
  - [x] Remove old branches
