### ISSUE TITLE
Reimplement Finance Contracts

### ISSUE THREAD

**Issue by corbanvilla** [owlprotocol/contracts#222]
Bring finance contracts back into master for next release.

**Contracts:**
- `EnglishAuction`
- `DutchAuction`
- `FixedPriceAuction`

- [x] #230
- [x] #226
- [x] Bring over all contracts (check with @corbanvilla or @HrikB on how to commit this)

**Note:** Leave out `Rent.sol` and `Bundle.sol` for now.

**Comment by vszammit** [comment]
finished documentation on all finance contracts and on README
