### ISSUE TITLE
Lootbox test consistency

### ISSUE THREAD

**Issue by corbanvilla** [owlprotocol/contracts#373]
Some of the lootbox tests fail with epoch tests. I think this is just due to slow runners. Implement some concurrent requests to prevent this.

**Comment by HrikB** [comment]
If you are unable to alleviate the inconsistency... perhaps better just keep that as a solidity test and remove the JS/TS test altogether

**Comment by corbanvilla** [comment]
@HrikB I'm good with that if it's ready 👍
